language: rust
rust:
- stable

dist: xenial
addons:
  apt:
    packages:
    - xorg-dev
    - libglu1-mesa-dev

after_success:
- echo Success

jobs:
  include:
  - stage: version 1
    os: linux
    script: echo "Hello world"
  - stage: build 2
    os:
    #- windows
    - linux
    - osx
    script: echo "building..." #cargo build -v
