jobs:
  include:
  - stage: version 1
    script: echo "Hello world"
  - stage: test 2
    os:
    - linux
    - osx
    language: rust
    rust:
    - stable
    dist: xenial
    addons:
      apt:
        packages:
        - xorg-dev
        - libglu1-mesa-dev
    script: echo "building..." #cargo build -v
    after_success:
    - echo Success
