os:
#- windows
- linux
- osx
language: rust
rust:
- stable

dist: xenial
addons:
  apt:
    packages:
    - xorg-dev
    - libglu1-mesa-dev

before_install:
- ./scripts/before.sh

script:
- cargo build --release

after_success:
- echo Success
