os:
- windows
- linux
- osx
language: rust
rust:
- stable

branches:
  except:
  - /^[0-9]\.[0-9]\.[0-9]/

dist: xenial
addons:
  apt:
    packages:
    - xorg-dev
    - libglu1-mesa-dev

before_install:
- ./scripts/before.sh

script:
- cargo build --release

after_success:
- ./scripts/after.sh
