os:
#- windows
- linux
- osx
language: rust
rust:
- stable

dist: xenial
addons:
  apt:
    packages:
    - xorg-dev
    - libglu1-mesa-dev

after_success:
- echo Success

jobs:
  include:
  - stage: version
    script: echo "Hello world"
  - stage: build
    script: echo "building..." #cargo build -v
