[package]
name = "drawing"
version = "0.1.0"
authors = ["Brent Gardner <bgardner@squarelabs.net>"]
edition = "2018"

[dependencies]
piston = "0.40.0"
piston2d-graphics = "0.29.0"
pistoncore-glutin_window = "0.52.0"
piston2d-opengl_graphics = "0.58.0"
