[package]
name = "rsui"
version = "0.1.0"
description = "A cross-platform UI library for Rust"
authors = ["Brent Gardner <bgardner@squarelabs.net>"]
edition = "2018"

[dependencies]
piston_window = "0.87.0"
pistoncore-glfw_window = "0.47.0"
